<?php
class Controller_Main extends Controller{
    function action_index()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
        $this->view->generate('main_view.php', 'template_view.php');
    }

}