<?php
class Controller_Post extends Controller{
    function __construct()
    {
        $this->model = new Model_Post();
        $this->view = new View();
    }

    function action_index()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
        $data = $this->model->get_data();
        $this->view->generate('post_view.php', 'template_view.php', $data);
        var_dump($data);
    }
}